# Generated by Django 4.0.1 on 2022-01-29 11:13

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='media/blogs-thumbnail/%Y/%m/%d/')),
                ('title', models.CharField(max_length=100)),
                ('mins_required', models.IntegerField()),
                ('blog_desc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
